Style/StringLiterals:
  Exclude:
    - "spec/unit/fixtures/**/*"
    - "lib/chef-cli/skeletons/**/*"
Layout/TrailingWhitespace:
  Exclude:
    - "spec/unit/fixtures/**/*"
Style/PercentLiteralDelimiters:
  Exclude:
    - "lib/chef-cli/skeletons/**/*"
Layout/TrailingBlankLines:
  Exclude:
    - "spec/unit/fixtures/**/*"
