# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-ws-notify

# Which Ruby Gems, built when the Omnibus package is built, to publish to rubygems.org
# This publish is triggered by the `built_in:publish_rubygems` artifact_action.
rubygems:
  - chef-dk
  - chef-cli

pipelines:
  - verify:
      public: true

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # The tag format to use (e.g. v1.0.0)
  version_tag_format: "v{{version}}"
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"

changelog:
  rollup_header: Changes not yet released to stable

# These actions are taken, in order they are specified, anytime a Pull Request is merged.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_version.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - built_in:build_gem:
      only_if:
        - built_in:bump_version

subscriptions:
  - workload: artifact_published:unstable:chefdk:{{version_constraint}}
    actions:
      - built_in:build_docker_image
  - workload: artifact_published:current:chefdk:{{version_constraint}}
    actions:
      - built_in:tag_docker_image
  - workload: artifact_published:stable:chefdk:{{version_constraint}}
    actions:
      - built_in:rollover_changelog
      - built_in:publish_rubygems
      - built_in:notify_chefio_slack_channels
